Django6620hw4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('shop/', include('shop.urls')),
    path('admin/', admin.site.urls),
]

shop/urls.py
from django.urls import path

from . import views

app_name='shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:product_id>/add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('<int:product_id>/add/', views.add, name='add'),
    path('<int:product_id>/remove/', views.remove, name='remove')
]

shop/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=100)
    img = models.CharField(max_length=200)
    info = models.CharField(max_length=200)
    amt = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class User(models.Model):
    username = models.CharField(max_length=50)
    cart = models.CharField(max_length=2000)

    def __str__(self):
        return self.username

shop/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render
from django.urls import reverse

from .models import Product, User


def index(request):
    user = User.objects.get(id=1)
    product_list = Product.objects.all()
    template = loader.get_template('shop/index.html')
    context = {
        'product_list': product_list,
        'username': user.username
    }
    return HttpResponse(template.render(context, request))

def add_to_cart(request, product_id):
    user = User.objects.get(id=1)
    user.cart = str(product_id) + "," + str(user.cart)
    user.save()

    return HttpResponseRedirect(reverse('shop:index'))

def add(request, product_id):
    user = User.objects.get(id=1)
    user.cart = str(product_id) + "," + str(user.cart)
    user.save()
    return HttpResponseRedirect(reverse('shop:cart'))

def remove(request, product_id):
    user = User.objects.get(id=1)
    user.cart = str(user.cart).replace(str(product_id) + ",", "", 1)
    user.save()
    return HttpResponseRedirect(reverse('shop:cart'))

def cart(request):
    user = User.objects.get(id=1)
    # not use first element
    product_amt = [-1, 0, 0, 0, 0]
    products = str(user.cart).split(',')
    while '' in products:
        products.remove('')

    for x in products:
        product_amt[int(x)] += 1

    print(product_amt)

    product_list = []
    if products:
        product_list = Product.objects.filter(id__in=products)
        for x in product_list:
            product = Product.objects.get(id=x.id)
            product.amt = product_amt[x.id]
            print(product.amt)
            product.save()

        product_list = Product.objects.filter(id__in=products)

    template = loader.get_template('shop/cart.html')
    context = {
        'product_list': product_list,
        'username': user.username
    }
    return HttpResponse(template.render(context, request))

shop/templates/shop/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
        ul {
            margin: 30px;
        }

    </style>
</head>
<body>


<div class="container">

    <ul class="nav justify-content-end">
        <li class="nav-item">
            <a class="nav-link fs-4" href="{% url 'shop:index' %}">Home</a>
        </li>

        <li class="nav-item">
            <a class="nav-link fs-4" href="{% url 'shop:cart' %}">Shopping Cart</a>
        </li>

        <li class="nav-item">
            <a class="nav-link fs-4" href="#">{{ username }}</a>
        </li>
    </ul>



    <div class="container">
        <h2>Shopping Cart</h2>
        {% if product_list %}
            {% for product in product_list %}
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">Number: {{ product.amt }}</p>
                        <form action="{% url 'shop:add' product.id %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="Add">
                        </form>
                        <form action="{% url 'shop:remove' product.id %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="Remove">
                        </form>
                        <br>
                    </div>
                </div>
            {% endfor %}

        {% else %}
            <p>Your shopping cart is empty.</p>
        {% endif %}

    </div>

</div>


</body>

</html>

shop/templates/shop/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Title</title>

    <style>
        ul {
            margin: 30px;
        }

        img {
            height: 200px;
        }
    </style>

</head>
<body>

<div class="container">

    <ul class="nav justify-content-end">
        <li class="nav-item">
            <a class="nav-link fs-4" href="{% url 'shop:index' %}">Home</a>
        </li>

        <li class="nav-item">
            <a class="nav-link fs-4" href="{% url 'shop:cart' %}">Shopping Cart</a>
        </li>

        <li class="nav-item">
            <a class="nav-link fs-4" href="#">{{ username }}</a>
        </li>
    </ul>



    <div class="container">

        {% if product_list %}
            {% for product in product_list %}
                <div class="card" style="width: 30rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <img src={{ product.img }}>
                        <p class="card-text">{{ product.info }}</p>
                        <form action="{% url 'shop:add_to_cart' product.id %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="Add to Cart">
                        </form>
                        <br>
                    </div>
                </div>
            {% endfor %}

        {% else %}
            <p>No products are available.</p>
        {% endif %}

    </div>

</div>

</body>
</html>